### ISSUE TITLE
【开动脑洞】新功能提议专贴

### ISSUE THREAD

**Issue by rikumi** [HeraldStudio/herald-webservice#10]
我先开个头吧，大概可以从这几方面考虑：

1. 查询功能扩展（蹭课必备：根据课名搜教室）
2. 用户行为分析系列（将接口调用按用户区分入库，年终来一个大数据分析，夏至那天你查了36次成绩，你说这样能凉快一点）
3. 增进师生联系系列（先做找老师🤔）
4. 社交系列（个人主页，表白墙，匿名消息）
5. 社团活动系列（社团主页，社团动态）

**Comment by Vigilans** [comment]
社交系列上我有想过根据一卡通号发短讯，这样卡掉时可以很容易联系到失主什么的
但是考虑到有些人是视这些信息为隐私的（以及确实存在的一些问题） 可能需要谨慎对待……

**Comment by rikumi** [comment]
@Vigilans-Yea 感觉可以做个人主页，用一卡通号可以直接搜到，默认是几乎空白的（没有任何可能被视为隐私的信息），然后大家根据自身情况来添加信息，当然这首先需要先把社交圈子建好，否则没有生态就没人喜欢用了

**Comment by Vigilans** [comment]
@rikumi 不知为何感觉我身边的人不太想在这种全校范围（院范围都没啥人了）的半熟人圈子里交流（我是挺喜欢的，可能是错觉吧） 大概还是需要和社团等东西配套起来，建立一个有刚需的社交圈子吧

另外，好像有些人觉得一卡通号本身就是个隐私，不希望被利用啥的（有些同学吐槽过查课界面能同时查到学号和一卡通号 并且两种号都能查课）

感觉可以开学时在小猴上发布一个投票，看一看大部分人的需求和看法是怎么样的(〜￣△￣)〜

**Comment by sleepyjoker** [comment]
社交方面感觉可以加个类似贴吧知乎的问答平台，可以发一些求助帖之类的

**Comment by imfinethanks** [comment]
一卡通余额查询 可以出个月账单之类的

**Comment by tusooa** [comment]
> 用一卡通号可以直接搜到，默认是几乎空白的（没有任何可能被视为隐私的信息），然后大家根据自身情况来添加信息

为什么要几乎。。。我觉得所有信息都是隐私（
应该默认什么都不显示，除非用户同意显示

> 增进师生联系系列（先做找老师🤔）

我觉得这个挺好的，学校网站上教师信息特别（尬）

> 查询功能扩展（蹭课必备：根据课名搜教室）

【全校开课列表】？

**Comment by Vigilans** [comment]
> 查询功能扩展（蹭课必备：根据课名搜教室）

这个东西和空教室基本是一体两面的啊……我来做吧（正好名正言顺把模块做成一个文件夹）（然而还在外面浪……踩个自己先

**Comment by FuuuOverclocking** [comment]
提个积德的功能↓
用户可以点暗恋某人，如果对方也点了自己，就立刻通知双方。
没有性别数据，觉得同性恋必须支持。
为防止有人把周围人点一遍，获取

**Comment by FuuuOverclocking** [comment]
所有人的态度，导致失去意义，建议每周最多可以改一次，至多同时选2人。
↑只能选1个可能制造的cp太稀少，多于3个...感觉站长脸上增光。

> 求助帖和投票
赞成
另外感觉用姓名代替一卡通号为索引比较好，姓名总是公开的..

**Comment by FuuuOverclocking** [comment]
建议小猴出个**基于标签的事项和讨论功能**。
### 解释
现在大家（至少周围人）基本都是用QQ

* 发全体消息、发公告的方式来通知参与某个活动的人 **很不专业，通知也容易水群水没，也缺少日程提醒**
* 讨论课程的题目/项目 **往往只能单发消息问个别大佬，或者发班群里，讨论不起来**

参考StackOverflow，知乎，Coursera的课程论坛，我提个这样的功能

* 每个人都可以创建标签
* 每门课程都预创标签
* 每个人可以浏览所有标签，并给自己添加标签
* 每个标签下都有 逼事列表和讨论帖，逼事列表任何人都可以编辑（参考wiki式），添加标签的人会收到日程提醒；讨论帖有顶踩，优质答案上升，并把Stackoverflow的威望值和徽章制度搬过来用来激励大佬
* 标签之间的关系：父子？高相关？......
* 标签上的内容具有公开性，私下的东西归QQ私下发送
### 可能遇到的问题
需要更多服务器资源：建议小猴仅充当数据平台，数据放在APP客户端，仅储存一个月内活跃的标签数据；当存着过期标签的客户端再次访问该标签时，从客户端取数据重新活化标签

如何保存图片，文件：增加预算😂

公开编辑内容恶意被改：[维基百科是如何防止恶意修改的？ -知乎](https://www.zhihu.com/question/21074040)

**Comment by tusooa** [comment]
参考 [Canvas](https://www.canvaslms.com/)。
https://www.canvaslms.com/higher-education/
好像很多学校在用。。。

**Comment by higuoxing** [comment]
不知道写个socket把以前log的功能做到管理界面怎么样... 脑洞而已，你们看呢
今天预约上游挂了，明天再看看

**Comment by tusooa** [comment]
tee和tail -f
和socket。。。有什么关系吗。。。

--- 原始邮件 ---

发件人： "higuoxing" <notifications@github.com>
已发： 2018年4月17日 下午10:48
收件人： "HeraldStudio/herald-webservice" <herald-webservice@noreply.github.com>
抄送： "ThisTusooa" <tusooa@vista.aero>, "Comment" <comment@noreply.github.com>
主题： Re: [HeraldStudio/herald-webservice] 【开动脑洞】新功能提议专贴 (#10)



不知道写个socket把以前log的功能做到管理界面怎么样... 脑洞而已，你们看呢
今天预约上游挂了，明天再看看

―
