### ISSUE TITLE
RFC: 清理历史遗留代码

### ISSUE THREAD

**Issue by unconsolable** [HeraldStudio/herald-webservice#111]
目前的 WebService 4 中有很多历史遗留代码，由于学校内系统更新等原因，已经不再适用。比如 
* https://github.com/HeraldStudio/herald-webservice/blob/v4/routes/api/laundry.js
* https://github.com/HeraldStudio/herald-webservice/blob/v4/routes/api/gpa.js
* https://github.com/HeraldStudio/herald-webservice/blob/v4/routes/api/phylab.js

对于这些历史遗留代码，可以考虑清除，在对这些接口调用时，返回以适当的错误信息。如对 SRTP 查询，报错功能不支持等。

可能的实现方法：
* 清除已有接口文件，对调用直接 throw 
* 从中间件开始重新构造，选用一门热度尚可~~不会没饭吃~~的语言从 0 重建，同时尝试部署假数据及单元测试，保证基本功能的稳定。

可能的基本功能：
查课表，查校历，查余额，校车班次，自定义课程，查跑操，体测成绩。

cc. @R-shrug @Karshilov @Wave-SYJ

**Comment by Wolf-Tungsten** [comment]
建议使用更具创新性的功能替代，或者使用东大信息化App



靡不有初&nbsp;鲜克有终


------------------ 原始邮件 ------------------
发件人: unconsolable ***@***.***&gt;
发送时间: 2022年1月13日 22:09
收件人: HeraldStudio/herald-webservice ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [HeraldStudio/herald-webservice] RFC: 清理历史遗留代码 (Issue #111)





 
目前的 WebService 4 中有很多历史遗留代码，由于学校内系统更新等原因，已经不再适用。比如
  
https://github.com/HeraldStudio/herald-webservice/blob/v4/routes/api/laundry.js 

https://github.com/HeraldStudio/herald-webservice/blob/v4/routes/api/gpa.js 

https://github.com/HeraldStudio/herald-webservice/blob/v4/routes/api/phylab.js 
 
对于这些历史遗留代码，可以考虑清除，在对这些接口调用时，返回以适当的错误信息。如对 SRTP 查询，报错功能不支持等。
 
可能的实现方法：
  
清除已有接口文件，对调用直接 throw 

从中间件开始重新构造，选用一门热度尚可不会没饭吃的语言从 0 重建，同时尝试部署假数据及单元测试，保证基本功能的稳定。 
 
可能的基本功能：
 查课表，查校历，查余额，校车班次，自定义课程，查跑操，体测成绩。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
