### ISSUE TITLE
图书馆接口返回数据

### ISSUE THREAD

**Issue by MediosZ** [HeraldStudio/herald-webservice#20]
renewDate 返回的是续借次数，不是时间

续借必须在到期前多少天内啊
感觉可以加一个能否续借的标志（或者做在前端

**Comment by sleepyjoker** [comment]
renewDate这个通神要背锅（滑稽，我写的times可能通神理解错意思了，在命名规则更改的时候给改成了renewDate；
续借好像是在到期7天前可以，不太确定，但是续借失败的话会返回失败的原因

**Comment by MediosZ** [comment]
可以用renewCount ？
如果不在续借期内续借和其他原因续借失败返回的结果不一样吧？

**Comment by sleepyjoker** [comment]
不一样，比如有超过最大续借次数，未到借阅时间等


| |
qiaozhf
邮箱：qiaozhf@163.com
|

签名由 网易邮箱大师 定制

在2018年03月04日 22:26，MediosZ 写道：

可以用renewCount ？
如果不在续借期内续借和其他原因续借失败返回的结果不一样吧？

**Comment by rikumi** [comment]
QAQ

**Comment by rikumi** [comment]
QAQ
