### ISSUE TITLE
【上游故障】旧版信息门户疑似下线

### ISSUE THREAD

**Issue by rikumi** [HeraldStudio/herald-webservice#21]
[旧版信息门户](http://myold.seu.edu.cn) 疑似已下线，目前没有恢复迹象。

该服务影响到 WS3 的功能有两个：

1. auth 中间件登录后，获取用户姓名学号的请求（[代码](https://github.com/heraldstudio/herald-webservice/blob/master/middleware/auth.js#L151)）；
2. user（本科生用户信息）接口（[代码](https://github.com/heraldstudio/herald-webservice/blob/master/api/user.js#L5)）；

上述接口都可以直接在新信息门户找到对应的信息（参考 [webserv2 登录新信息门户的实现](https://github.com/HeraldStudio/webservice-py/blob/master/mod/auth/newHandler.py)），但新信息门户必须单独登录<sup>[1](#fn1)</sup>且登录需要验证码。

而验证码平台目前缺乏横向可扩展性和对爬虫集群的支持，建议只在 python 层保留 CNN 识别，将验证码图片的获取和识别结果的提交交给 Node 层，层间使用 IPC 通讯。

<a name="fn1">[1]</a>: webserv2 中，登录认证有两种方案：东大 App 方案和新信息门户方案。东大 App 方案为 ReSTful 接口，方便调用，无需验证码；新信息门户方案需要验证码识别，较为复杂；两者稳定性不相上下。WS3 中目前采用的是东大 App 方案。违背常理的是（初步观察，待证实），进入新信息门户必须单独通过认证，任何其他站点的 Cookie 都无法避开新信息门户认证过程，因此不能使用东大 App 方案得到的 Cookie 直接进入新信息门户，可以理解为新信息门户的 Cookie 适用范围最广。

**Comment by tusooa** [comment]
但是我登陆真的不用验证码啊。。。？
