### ISSUE TITLE
【意见征集】上 TypeScript 吼不吼哇

### ISSUE THREAD

**Issue by rikumi** [HeraldStudio/herald-webservice#25]
从 Atom 转到 VSCode 之后想做的第一件事（

上 TypeScript，工作量可能稍微有点大，涉及到 kf 之类的框架都要改，但是对以后开发有好处，而且支持装饰器，缓存中间件有福了🤔

**Comment by rikumi** [comment]
然后 ORM 可以考虑统一为行业标杆 TypeORM

**Comment by higuoxing** [comment]
没用过耶，可以尝试一下...
