### ISSUE TITLE
【开动脑洞】微信公众号还可以用来干哪些事

### ISSUE THREAD

**Issue by rikumi** [HeraldStudio/herald-webservice#26]
如题，基于自动回复、自定义菜单、模板消息这些，求脑洞🤔（没错我现在闲的很）

先吸屁股去了🤔

**Comment by Raaabbit** [comment]
性格测试，星座运势，文字游戏.........比如“sheepQAQ今天不会有bug”，“sheepQAQ是一个可爱的男孩子”

**Comment by rikumi** [comment]
想看楼上女装.jpg

**Comment by tusooa** [comment]
「今天物理会不会挂」

1. 由「物理」匹配到「基础物理学（1）」
2. 考察之前的成绩（如果有）
3. 输出挂的概率，或者「不知道」

**Comment by rikumi** [comment]
很应景
