### ISSUE TITLE
仪科学院通知无法进入

### ISSUE THREAD

**Issue by Sciroccogti** [HeraldStudio/herald-webservice#30]
### 点击任意通知都弹出“_部分接口请求失败_ ”

手机传图失败QAQ

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 MI6 发送_

**Comment by Sciroccogti** [comment]
![screenshot_2018-07-09-13-57-46-295_com opera mini native beta](https://user-images.githubusercontent.com/32357397/42434382-9342b202-8385-11e8-87e7-1a6470162df1.png)

**Comment by Wolf-Tungsten** [comment]
需要辅助调试信息，请提供无法访问的通知的URL网址，谢谢！

**Comment by Sciroccogti** [comment]
@Wolf-Tungsten 

[东南大学．联想"穿戴式心脏．睡眠一情绪智昨天能监控联合实验室学术委员会成立](https://myseu.cn/#/notice/url/http%3A%2F%2Fins.seu.edu.cn%2F2018%2F0708%2Fc2324a232664%2Fpage.htm)

**Comment by Wolf-Tungsten** [comment]
问题已修复

**Comment by tusooa** [comment]
这是由于 `depts.json` 里没有定义 `contentSelector`，从而 `cheerio` 返回的内容为空，因此返回值是 `koa` 默认的 404。

**Comment by tusooa** [comment]
我当时在编写这个模块的时候并不知道这个 POST 是要在 web 被调用的，没有考虑这个属性，漏掉了。而之后我一直使用 App，并没有遇到这个坑。感谢您对此问题的反馈。希望在您和更多人的支持下，小猴偷米会变得更加完善。

**Comment by Sciroccogti** [comment]
@tusooa 不客气

如果没认错的话我应该是你曾经的舍友了2333

**Comment by Wolf-Tungsten** [comment]
请不要在此处讨论无关的话题。
