### ISSUE TITLE
关于后端框架设计与相关规范的提议

### ISSUE THREAD

**Issue by Vigilans** [HeraldStudio/herald-webservice#4]
# 主要提议

1. 保留Node.js模块，作为中间件使用。
2. 分模块开发，各模块独立运行，由中间件进行路由。
3. 为模块及模块的每一个子组件编写简要的文档。

以上提议的出发点是：让后来的同学可以快速上手，专注于新功能的开发/细节的完善，而不是反复重构前人的代码，以及陷入因技术栈选择而产生的内耗。

以上只是一些不成熟的提议，在此抛砖引玉，希望能让后端开发尽快顺利运作起来~

以上。

**Comment by Vigilans** [comment]
# 具体方案
## 中间件
### 出发点

1. 方便版本迁移。可以在WebService3完成开发之前，由中间件决定传入的API是路由到2代还是3代，从而顺利完成从2代到3代的过渡。
2. 方便模块控制。每个模块编写为一组独立的服务，由一个对应的中间件来决定路由机制。这样，每个模块可视为整个后端服务的一个插件，可以方便地被插入与删除，增强了框架的扩展性。
3. 方便添加预处理请求/响应的功能。比如我想要添加的代理功能，或许就可以通过添加一个中间件来达成。


### 简要设计

每一个中间件单独编写为一个JS文件，相关的参数写在JSON配置文件中。

作为模块的中间件，应当具有如下功能：

* 路由
* 版本控制

由于以上基本操作是共通的，因此可以写一个模块中间件的基类，定义一些基本的使用模式。后来人在添加模块时，若不想要额外的逻辑，只需在JSON文件中添加相关配置后使用这个基类即可。


## 分模块开发
### 出发点

1. 方便新功能的添加与管理。以后想要添加的新功能中，有些或许并不是整个团队一起开发，而是某个人的兴趣与意愿。开发一个独立的模块，再作为插件整合入后端主服务中，或许是一个不错的模式。

2. 让开发者可以尽量自由地选择技术栈。以后小猴可能会添加各种各样的新功能，而Python/JS等并不一定是最好的选择。这时，分模块开发可以让他们自由选择喜欢的技术进行开发与维护。
   小猴偷米作为一个自由、开放的团体，也应当鼓励技术的多样性吧~而不是为技术选择所累╮(╯-╰)╭

3. 据了解，今年有一些SRTP项目就是针对小猴还没有的功能制作校园服务类App（水不水就另说啦）。从这一点出发，其实也可以考虑为外部人员贡献新功能提供一定的支持，而模块机制就带来了这样的可能。


### 简要设计

1. 一个**模块**应是一套完整的、相互联系的中规模功能集合。
   比如：转发学校服务的爬虫集WebService，或是这个仓库的README中提到的AppService等。
   在此把模块内的每个子功能称为**组件**。

2. 不同模块间可以使用不同的语言。
   同一个模块内的所有组件必须使用同种、同版本的语言。

3. 一个模块应是一个独立的服务器应用。
   每个模块应能作为一个独立的程序运行、测试，对外提供RESTful API接口服务。
   由中间件模块负责各个模块的接入。

4. 每个模块可独立进行开发。
   由于每个模块是一个独立的应用，因此可单独使用一个Git仓库开发，最终整合至主仓库中。
   建议用`git subtree`命令进行整合与管理。

5. 模块可打包成docker镜像发布。
   每个镜像中包含可运行该模块的最小依赖环境，从而避免了主服务器的污染，也方便了模块在不同服务器间的迁移。

6. 此外，每个模块应有统一的部署方法，方便未来实现自动化部署。


## 文档规范

### 出发点

1. 让不同的开发者以及后来人能够快速学习、上手。
2. 方便前端开发对API的查阅、使用。
3. 写文档的过程也能协助开发者自己理清思路。


### 简要设计

文档主要分为两种：模块文档与子组件文档。
每当开发者开发完一个模块/子组件后，都应该留下一份简单的文档。
每个文档不需要什么复杂的内容，只需一个readme.md或是一个wiki页面即可。

#### 各种文档的大概要求如下：

**模块文档：**

* 模块readme：大家商量吧~

* 模块wiki：记录一些通用、系统的开发知识。
   如主仓库中可以有中间件编写、模块开发规范介绍的wiki页等。

**子组件readme应至少包含:**

* API表。写明HTTP Method、Url、功能描述即可。

* 大体设计思路。较复杂的功能实现也可单独拿出来说明一下。

* To-do list。包含已实现功能，将实现功能，以及未来期望实现的功能。

* 贡献者。包含学号、姓名，以及指向Github Profile的超链接。
  任何对该子组件有commit的人都可以在readme中添上自己的名字。既然有所贡献，就大大方方地留下自己印记，让后来人了解一下嘛~出问题的时候也能找到接锅侠(～￣▽￣)～


参考：[空教室组件readme](https://github.com/Vigilans-Yea/HeraldWS3/blob/spare-classroom/api/spare-classroom/readme.md)


## 其他

* 建议以后在开发上有问题的话，最好能开issue来提问，之后不管是等人回答还是去群里请人回答都可以。
  尽管看起来有点麻烦，这样做的好处是可以留下记录，方便后来人查阅，也是快速学习上手的一种资料。

* 总之，一个丰富的Github Repo相信是很能激起未来的学弟~~学妹~~们的学习兴趣的吧！

**Comment by Wolf-Tungsten** [comment]
建议研究下这些srtp项目都想做什么，然后借鉴开发有效功能

**Comment by rikumi** [comment]
问题的中心在于如何在开发灵活性和可维护性中取得平衡。

原来的 webserv2 系统，规模非常庞大，单个模块也非常复杂，连一个重用的 `BaseHandler` 都没有，开发不方便，维护也不方便。

开发 webserv3 的最主要目的是让我们更好维护，但如果能借这个机会提升一下灵活性，同样是好的。换句话说，可维护性第一，开发灵活性第二。如果真的改成用 docker 和中间件相互支撑的多个系统，恐怕可维护性要打折扣了。

之前用 Node 的时候，我也给出了一个不太成熟的平衡两者的思路，大体来讲是这样的：

- 统一规定模块的语言和实现方式。基于 kf-router 开发的模块一方面易于书写，上手快，另一方面模式简单且统一，容易维护；
- 所有模块作为一个项目，在一个进程中运行，防止了进程分离导致的资源浪费、可能需要用到进程间通信等问题；
- 借助 kf-router 文件路由，让每个模块可以单独开发，并且即插即用，动态添加模块甚至不需要重启程序。

写 Node 版的时候，我也没有特别在意这种模式，只是随着心里对优雅的理解去写了；但是现在看来这种方法应该是比较优雅的，平衡两者的解决方案。当然他也有缺点，我目前觉得缺点主要是两个，一个是不容易编写特别大的模块，另一个是强迫新人学习一种语言（这在可维护性的要求下几乎是必须的，否则维护者将面临不可避免的语言级重构）。

改为 Python 之后，其实事情就变得复杂了，尤其是开发灵活性上受到了一点打击。主要原因在于 Node 的模块机制是黑盒的，你必须通过导入导出来使用另一个文件的模块。文件与文件之间的耦合很低；而 Python 的模块机制是白盒的，文件与文件之间的耦合会更深一层。 

总之，这又是一个 Android 阵营和 iOS 阵营的互掐问题：一个是究极灵活究极难维护，一个是不太灵活但究极可维护。但我觉得咱们的语境是小猴的核心系统，可维护性已经不是可以随便忽略的小问题了。如果继续用 Python 的话，尽量把模块做小，耦合做低，让每个 Handler 能满足独立可开发吧。

**Comment by rikumi** [comment]
# 驱除 Python 恢复 Node
This is the point

**Comment by Wolf-Tungsten** [comment]
看你们神仙打架

**Comment by higuoxing** [comment]
复习傻了...观望一波...doker-compose感觉不是很好的方法...要写挺多config吧...唉，nginx的配置还不能写的好看...Node我觉得是可以的

**Comment by Vigilans** [comment]
@Higuoxing 

> nginx的配置还不能写的好看

用Node路由的话，Nginx只需要配置一个Node一个服务就可以了吧？
我的提议里面，Node是外部连接到后端服务的唯一入口来着……传入的API经中间件转发到其他的localhost应用上。

**Comment by Vigilans** [comment]
@Wolf-Tungsten 

> 建议研究下这些srtp项目都想做什么，然后借鉴开发有效功能

╮(╯-╰)╭记得不太清楚了...我个人觉得有些是比较边缘的功能，目前不应该被提上议程。

我的想法是这些功能就让别人有兴趣的去做，如果做得好的话，小猴就可以试着简单改造适配一下，添加成一个新功能；而分模块方案就可以比较方便的做这种事……因为他人写的模块只需要是一个可以独立运行的服务端程序就好了。

**Comment by Vigilans** [comment]
@rikumi 

在提议里面，我认为「模块」应该是一个 *中规模* 的功能集合，而这个「中等」是相当于整个后端系统而言的。因此，一个模块的规模应该是很大的，而非随意切割。

对于WebService项目，我认为就应该只用一个模块编写，内部全部使用Python3，而不是将其中的几个API抽出来用其他语言另写一个模块什么的。

因此，说是分模块开发，但在后端重写的可预期的时间里，除开中间件也就只有WebService一个模块了……

---
> 但我觉得咱们的语境是小猴的核心系统，可维护性已经不是可以随便忽略的小问题了

关于可维护性，我是这样想的：
1. 目前小猴的核心系统是WebService。在提议中的设计下，要承担的工作由原来的一个Python项目变成了Node.js模块 + Python模块。 在两种模式下：

   * Python部分要做的事基本是一模一样的，最终提供的都是一个可以独立运行的服务端App。

   * 相较于前者，后者增加的Node.js中间件可以提供版本控制功能，使我们不必写完所有的API后才将WebService3正式上线。

   因此在WebService的语境下，对于提议的方案，感觉可维护性并没有受到明显的打击。除此之外，个人认为其提供的版本过渡能力也是十分有价值的。不过，这只是我提出的一种可能的迁移方案而已，通神有其他的方便版本迁移的构思吗？

2. 个人认为适合新开一个模块的情况举例：

    * 服务与目前的WebService爬虫集技术关联不大，而又有一定规模的时候。
      比如README「新功能提案」中提到的「广告自助发布审核系统」等。

    * Python不是最适合语言，同时也有相当的规模的时候。
      比如，如果以后我想做一个chat bot接入到小猴中，用M$的Bot Framework的话，C#/Node.JS是最好的选择。这种情况下，对于那些有兴趣开发的人，一个较自由的技术栈明显能提供更大的动力吧？

    总之，分模块开发是为了小猴以后添加一些更宏大的新功能所准备的，相比之一个只使用Python、采用同一架构的庞大无比的项目，细分一下子模块或许更有利于结构上的维护。


3. 如果技术栈足够开放的话，在招新的时候，或许也更容易找到喜欢做相关技术的人来维护。
   同时，小猴的这些项目也给了那些想学习这些技术的人一次绝好的锻炼自己的机会。

**Comment by jayjliang** [comment]
版本迁移的方式应该是在路由层做控制最好吧，不知道你们现在的架构是怎样的，原来的架构就在auth里面去做控制就可以了，不过需要稍微改造下来支持下版本。
不同版本建议路由里加上版本号，例如v1,v2,这样多个版本共存还是比较容易的。
学弟最后讲的那个node模块我理解起来和我们之前的auth是一样的，只不过以前是使用python来实现的
