### ISSUE TITLE
授权方案讨论

### ISSUE THREAD

**Issue by Vigilans** [HeraldStudio/herald-webservice#5]
### How to define？
是根据角色授权（管理员、学生、老师，etc）

还是根据行为作用域授权（行为好像基本只有读没有写……不过可以继续细分查跑操/成绩等的权限？用OAuth做，~~带上一点点以后成为学校统一接口的野心Σ(っ °Д °;)っ……？~~）？

or 两者都有？

### ~~What's your name？~~
~~authentication与authorization缩写都是auth...新的中间件要叫什么...~~

### My Proposal
* 就授权功能，写一个`identity.js`中间件。

   这个中间件判断token对应的用户信息是否符合API的授权标准，从而决定是否路由。

   实现方面，可以考虑使用decorator语法，即在每个API函数前加上authorize decorator，用于描述当前API的授权要求。如：

   ```javascript
   export.route = {
     @authorize({ role: "Admin, Student" })
     async get() {
       // Logic codes... 
     }
   }
   ```

   此外，也可以对某个组件整体要求授权，然后对于个别API使用`@allowAnonymous`这样的decorator来允许无授权通过（乃至认证？）

* 将认证相关的属性统一放在`ctx.user`或`ctx.identity`属性中。即:
   ```javascript
   ctx.user = {
     token,
     cardnum,
     password,
     cookie
   }
   ```
   与用来保存请求体的`ctx.query`形成同级的对应。
   最终，这些由中间件添加的属性可以统一写在文档里面。
   
### Nonsenses
* 总感觉按上面写的话，命名有点混乱……称授权中间件为identity感觉有点奇怪……反而是认证中间件更合适一点——”取得身份信息“。两个auth中间件都写成全名或许会好一点。

* `/api/auth`直接在中间件中就被处理了，个人觉得结构上有种不严整感？不知道会不会让未来的新人在读API时感到困扰...改成传入`/api/auth`时则路由到对应的api文件，中间件主体用来处理认证信息，是否合适？

**Comment by rikumi** [comment]
> How to define？

授权中间件主要目的是允许第三方访问用户相关信息，即允许第三方获得一个受限的用户 token，第三方可以持有该 token 查询该用户的部分数据。授权中间件最好采用 OAuth2 方式，并提供一个前端页面以便用户提供授权。为了用户安全性考虑，授权页面可能要做成前后端不分离的。

授权中间件确实可以先不做……有兴趣也可以考虑下怎么实现。

> What's your name？

命名问题我也考虑过，考虑语言标准的做法可以是把 auth 让给授权，认证改用 verification，但 verification 又太长；可以考虑用 a11n 表示 authorization，a12n 表示 authentication；也可以考虑直接把授权跟认证直接写在一个中间件里，按代码片段区分。

> My Proposal

昨天我也查了一下 decorator，目前似乎只有 TypeScript 提供了支持，ES7 decorator 似乎尚在提案中。

你讲的 identity.js 似乎不是授权，那个应该叫鉴权……

不过确实鉴权方面被我忽略了，但是我觉得有更好的做法，可以直接把 `ctx.user` 做成 `get-property`，当路由处理程序取 `ctx.user` 时自动拒绝未登录请求。对于登录请求的身份识别，再在路由处理程序里自行操作。

> Nonsenses

在原来的 herald_auth + webservice2 架构中，auth 请求直接被中间件截获是现行做法。

在中间件 [herald_auth](github.com/heraldstudio/herald_auth) 中，提供了 `AuthHandler` 用于截获认证请求，以及 `APIHandler` 用于向 webservice2 传递 API 请求。这次 WS3 的时候就把两个合并在 `auth.js` 里，将加解密过程并列编排，方便阅读和维护。

**Comment by Vigilans** [comment]
了解了。

对于用户的身份识别，可以考虑在user中添加一个role属性，方便API进行判断(〜￣△￣)〜
