### ISSUE TITLE
【样本征集】全自动绩点计算的可行性

### ISSUE THREAD

**Issue by rikumi** [HeraldStudio/herald-webservice#9]
写成绩查询的时候发现[教务处成绩查询](http://xk.urp.seu.edu.cn/studentService/system/toMain.action)有一列数据我们一直没用，这一列就是课程代码，仔细看了一下似乎蛮有用的，最主要的是，据我目前分析似乎有这样一个规律：**对于自己院系开的课（即前两位跟学号前两位一样，第三位不管），除社会实践外，只要第四位数是1的都算绩点，反之都不算（限选课研讨课第四位都是3）。**

所以大概可以按如下的规则全自动的确定是否算绩点：

0. 自己院系开的课，第四位是1，而且名字不叫「社会实践」的都算绩点；
1. 只要是十位数的，都是大类通识课（高数大物大英概率论都属于这类），算绩点；
2. 体育课算绩点（18M0x000）；
3. 物理实验算绩点（10021311、10021312）；
4. 政治课算绩点（130、150开头）；
5. 军理军训算绩点（86001010、86001100）；
6. 课程编号没有规律的特殊情况，如几何与代数（07011280）等算绩点。

算法应当按照上述顺序进行标记，剩下的课程筛除，然后自动计算平均绩点。

希望来自各院系的大家能把这个白名单列表补全，打开你们的[教务处成绩查询](http://xk.urp.seu.edu.cn/studentService/system/toMain.action)，对照课程编号看看有哪些例外，尤其是学化学和医学的例外情况可能比较多🤭，希望最后能做出全自动的绩点计算，就可以把算法直接写在后端里了，免得前端重复造轮子。

**Comment by tusooa** [comment]
算不算是学院规定啊。。要看教学计划啊。。。

要不爬一下 [全校开课列表](http://xk.urp.seu.edu.cn/jw_service/service/academyClassToLook.action) 把选修课剔掉。。。？只是不知道往年的怎么查。

**Comment by rikumi** [comment]
是看教学计划，但是通过课程编号可以大致推断，基本上都是必选和通识算，限选任选研讨课不算

**Comment by Vigilans** [comment]
### 一些反例（以后发现的都更新在这里）
09031010 程序设计基础及语言A
09031011 程序设计基础及语言B 
第四位均为3

**Comment by Vigilans** [comment]
### 一些规律总结（更新同上……）
0. [院系代号参考](https://zhidao.baidu.com/question/179924571.html)：
      补充：
      15 马克思主义学院（见[学院官网开课列表](http://marxism.seu.edu.cn/6718/list.psp)）
      57 网络空间安全学院

1. 除选修课外，不管课程是什么类型，有多少位，代码前三位应该都对应开课学院，或是某个组织。
   
   院系开课举例：
   **数学学院**
   **070**11280     几何与代数（B）
   **070**1119111 工科数学分析Ⅰ 
   **070**1120112 高等数学（A）Ⅱ 

   **物理学院**
   **100**2123111 大学物理（B1）Ⅰ 
   **100**21311     物理实验(理工) Ⅰ 

   **马克思主义学院**
   **150**31562 中国近现代史纲要
   **150**42782 思想道德修养与法律基础
   **150**12122 马克思主义基本原理

   **外国语学院**
   **170**0109112 大学英语高级课程2

   **体育系**
   **18M**02000 TY2体育2 

   其他非院系开的课程举例：
   **工培中心**
   **81**012060 工业系统认识1 
   **81**012070 工业系统认识1 

   **电工电子楼**
   **84**101915 电工电子实践初步A 
   **84**101926 数字逻辑电路实验B

   **武装部**
   **86**001100 军训（含理论课）
   **86**001010 军事理论 

2. 选修课代码有点诡异……感觉需要开学退改选时仔细确认一下
   
   **一般来说，选修课貌似是000开头的**：
   00034252 社会调查方法原理与实务
   0003410   音乐鉴赏 
   0003611   第二计算机语言matlab
   （写抢课代码时观察下学校接口的相关函数的话，会发现34, 36正好也是调用人文、自然时其中一个传入的参数？）

   **但是经管就不太一样了**：
   1403401 经济管理基础 
   emmm...

3. 最好能找到高数、几代与物理在A、B、C、D下各自的课程代码，以分析出3位往后3~4位的特征。

**Comment by tusooa** [comment]
我4.8满的绩点算出来没4.0满的高。。。。

**Comment by Vigilans** [comment]
@tusooa 90 4.0与85 4.0 看来是大多数都落在85~89了( ﹁ ﹁ ) ~→

**Comment by sleepyjoker** [comment]
有可能，好像85-90分这一档的话4.0的标准是满绩，但是4.8满绩的话只有3.8

**Comment by tusooa** [comment]
@Vigilans-Yea 不不。。肯定是有bug 
因为高级的课4.8的没算上去吧
然后就变成了3.98/4 和3.3/4.8这种奇妙的情况

**Comment by Sciroccogti** [comment]
工业系统认识似乎不算绩点。。
